name: My First Workflow
on: push
jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4

          - name: welcome message
            run: |
             echo "my sample github actions code"
             ls
             cat README.md
          - name: generate ASCI artwork
            run: cowsay -f dragon "run for your life" >> cow.txt

          # - name: list the file
          #   run: ls

          # - name: read the flie
          #   run: cat README.md

