name: My First Workflow
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
          - name: checkout repo
            uses: actions/checkout@v4
          - name: install cowsay program
            run: sudo apt install cowsay -y
          - name: execute cowsay
            run: cowsay -f dragon "run for your life" >> dragon.txt
          - name: text file exists
            run: grep -i "dragon" dragon.txt
          - name: raed file
            run: cat dragon.txt
          - name: list repo files
            run: ls -altr