name: multiple-jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: install nginx
          run: sudo apt update nginx -y
        
        - name: sleep for 30 secs
          run: sleep 30
    build-job-2:
        runs-on: ubuntu-latest # could be any os windows or mac-os
        steps:
        - name: sample output
          run: echo deploying.....

#every jobs will run in its own virtual machine, like ubuntu,mac or windows
