name: nodejs-dev

on: push

jobs: #can define multiple jobs in a single workflow file.
 first_job: #jobname name could be anything
    runs-on: ubuntu-latest
    steps:
    - name: step1
      run: echo "my step 1 is executing"

    - name: step2
      run: ls
    
    - name: step3
      run: cat README.md
