name: nodejs-dev

on: push

jobs: #can define multiple jobs in a single workflow file.
 first_job: #jobname name could be anything
    runs-on: ubuntu-latest
    steps:
    - name: including the checkout action
      uses: actions/checkout@v4 # copied form the actions # when use any actions instaed of run
      # we will mention uses

    - name: step1
      run: echo "my step 1 is executing"

    - name: step2
      run: ls
    
    - name: step3
      run: cat README.md
#this will fail the pipeline because this sction does not have access to the readme.md so to gain the action
# we will copy the repo content to our workflow to do that
# go to git hub market place in google and in marketplace search for checkout and include that

#instead of using 3 runs we can have one  like this

    - name: writting with singl line
      run: | #this pipe is used to run in a single step
        echo "mo pelo bahut bada"
        ls -altr
        cat README.md
        sudo apt install nginx -y 
    #any librabry which is not installed can be intalled with apt command.

#lesson-1
#we can write a shell script outside of our yml file and refer it into tis yml
    - name: passing svhell script path
      run: ./hello.sh